In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
import numpy as np

text = '커피 한잔 어때'

# 1. Tokenizer 객체 생성
tokenizer = Tokenizer()

# 2. 텍스트 학습
tokenizer.fit_on_texts([text])  # 여러개 넣을 수 있으므로 리스트로 전달

# 3. tokenizer 객체 출력
print("tokenizer: ", tokenizer)

# 4. 텍스트를 시퀀스로 변환
sequences = tokenizer.texts_to_sequences([text])
print("sequences: ", sequences)

# 5. 단어 인덱스 출력
word_index = tokenizer.word_index
print("word_index: ", word_index)

# 6. 인덱스 -> 단어 맵핑 출력
index_word = tokenizer.index_word
print("index_word: ", index_word)

tokenizer:  <keras.src.legacy.preprocessing.text.Tokenizer object at 0x7e2a7a635c10>
sequences:  [[1, 2, 3]]
word_index:  {'커피': 1, '한잔': 2, '어때': 3}
index_word:  {1: '커피', 2: '한잔', 3: '어때'}




---



**단어 빈도 수 세기**

In [2]:
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
       '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
       '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.',
       ]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)

# 출력되는 순서는 랜덤
print("단어 카운트: ", tokenizer.word_counts)
print("문장 카운트: ", tokenizer.document_count)
print("각 단어가 몇 개의 문장에 포함되어 있는가: ", tokenizer.word_docs)
print("각 단어에 매겨진 인덱스 값: ",  tokenizer.word_index)

# word_counts: 모든 문장에서 각 단어가 등장한 총 횟수
# document_count: 전체 문장의 수
# word_docs: 각 단어가 등장한 문장 수
# word_index: 빈도 높은 단어 순서대로 매겨진 인덱스 딕셔너리

단어 카운트:  OrderedDict({'먼저': 1, '텍스트의': 2, '각': 1, '단어를': 1, '나누어': 1, '토큰화합니다': 1, '단어로': 1, '토큰화해야': 1, '딥러닝에서': 2, '인식됩니다': 1, '토큰화한': 1, '결과는': 1, '사용할': 1, '수': 1, '있습니다': 1})
문장 카운트:  3
각 단어가 몇 개의 문장에 포함되어 있는가:  defaultdict(<class 'int'>, {'단어를': 1, '토큰화합니다': 1, '먼저': 1, '나누어': 1, '텍스트의': 2, '각': 1, '딥러닝에서': 2, '토큰화해야': 1, '인식됩니다': 1, '단어로': 1, '사용할': 1, '수': 1, '토큰화한': 1, '있습니다': 1, '결과는': 1})
각 단어에 매겨진 인덱스 값:  {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '단어로': 8, '토큰화해야': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '사용할': 13, '수': 14, '있습니다': 15}


In [3]:
texts = ['커피 한잔 어때', '오늘 날씨 참 좋네', '옷이 어울려요']

# 1. 토크나이저 생성 및 학습
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

# 2. 시퀀스로 변환
sequences = tokenizer.texts_to_sequences(texts)
print(sequences)

# 3. 단어 인덱스 출력
word_index = tokenizer.word_index
print("\n단어 인덱스: ", word_index)

# 4. 패딩 처리 (길이를 4로 통일)
print("\n시퀀스: ", sequences)
padded_sequences = pad_sequences(sequences, 4)
print("\n패딩된 시퀀스:\n", padded_sequences)

[[1, 2, 3], [4, 5, 6, 7], [8, 9]]

단어 인덱스:  {'커피': 1, '한잔': 2, '어때': 3, '오늘': 4, '날씨': 5, '참': 6, '좋네': 7, '옷이': 8, '어울려요': 9}

시퀀스:  [[1, 2, 3], [4, 5, 6, 7], [8, 9]]

패딩된 시퀀스:
 [[0 1 2 3]
 [4 5 6 7]
 [0 0 8 9]]


In [4]:
model = Sequential()
model.add(Embedding(input_dim = len(word_index)+1, output_dim = 5))
# Embedding: 숫자를 벡터로 바꿈
# input_dim: 단어 집합의 크기 → len(word_index)+1  (+1은 패딩 토큰 0을 위한 자리)
# output_dim: 각 단어를 임베딩할 벡터 차원 수 (여기서는 5차원)


embedding_output = model.predict(padded_sequences) # padded_sequences를 모델에 통과시켜 임베딩된 결과 추출
embedding_output

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 222ms/step


array([[[ 0.04407405,  0.04062026, -0.02707812, -0.03902701,
         -0.02925834],
        [-0.03975775, -0.03678274,  0.04259855,  0.038383  ,
          0.01855201],
        [ 0.01040816, -0.0041554 ,  0.02616686,  0.02821357,
          0.04362668],
        [-0.02587637,  0.03794867, -0.0494935 , -0.02899985,
         -0.02041932]],

       [[-0.0276729 ,  0.02204007, -0.03776469, -0.01492186,
         -0.00166984],
        [ 0.04536605, -0.00153788, -0.01218031,  0.00170889,
         -0.0392115 ],
        [ 0.00744742,  0.02299876, -0.04134593, -0.00754498,
          0.02586986],
        [-0.01033107,  0.02881089,  0.00643022, -0.00950092,
          0.00106251]],

       [[ 0.04407405,  0.04062026, -0.02707812, -0.03902701,
         -0.02925834],
        [ 0.04407405,  0.04062026, -0.02707812, -0.03902701,
         -0.02925834],
        [-0.01890606, -0.02374557,  0.02831174, -0.01982399,
         -0.01358796],
        [ 0.0153337 , -0.00418387, -0.03247987, -0.0378077 ,
          0