### **사이킷런을 이용한 DTM과 TF-IDF**

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',
]

vector = CountVectorizer()

print(vector.fit_transform(corpus).toarray())
print(vector.vocabulary_)  # "i" 가 없는 이유 → 기본 token_pattern이 2글자 이상 단어만 허용하기 때문

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


- CountVectorizer
    - BoW (Bag of Words) 방식 벡터화 도구
    - 문서 집합(corpus)을 받아서 → 단어 사전 만들고 → 각 문서를 단어 등장 횟수 벡터로 바꿔줍니다.

- vector.fit_transform(corpus)
    - fit: 전체 문장에서 단어 사전을 생성
    - transform: 각 문장을 단어 등장 횟수 벡터로 변환
    - 결과는 희소 행렬(sparse matrix) 로 나오지만, .toarray()로 일반 배열로 바꿈.

- vector.vocabulary_
    - 단어 사전(Vocabulary)을 딕셔너리로 보여줌.
    - "단어": 인덱스 번호 형태

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',
]

tfidfv = TfidfVectorizer().fit(corpus)
print(tfidfv.transform(corpus).toarray())
print(tfidfv.vocabulary_)

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


- TfidfVectorizer
    - 문서마다 자주 나오지만 전체 문서에서 흔한 단어는 가중치를 낮추고,
드물게 나오면 가중치를 높임.


### **코사인 유사도**

In [7]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

doc1 = np.array([[0,1,1,1]])
doc2 = np.array([[1,0,1,1]])
doc3 = np.array([[2,0,2,2]])

print('문서 1과 문서2의 유사도 :',cosine_similarity(doc1, doc2))
print('문서 1과 문서3의 유사도 :',cosine_similarity(doc1, doc3))
print('문서 2와 문서3의 유사도 :',cosine_similarity(doc2, doc3))

문서 1과 문서2의 유사도 : [[0.66666667]]
문서 1과 문서3의 유사도 : [[0.66666667]]
문서 2와 문서3의 유사도 : [[1.]]
